"""Build regular expressions from composable, typed Python objects."""

from importlib import metadata

from .constants import (
    CARRIAGE_RETURN,
    CHAR,
    DIGIT,
    END,
    END_OF_STRING,
    LETTER,
    NEWLINE,
    NOT_DIGIT,
    NOT_LETTER,
    NOT_N,
    NOT_NEWLINE,
    NOT_WHITESPACE,
    NOT_WORD,
    NOT_WORD_BOUNDARY,
    NOT_WS,
    START,
    START_OF_STRING,
    TAB,
    WHITESPACE,
    WORD,
    WORD_BOUNDARY,
    WS,
    N,
    R,
)
from .exceptions import RemagicException
from .interface import (
    after,
    any_of,
    at_least,
    atomic,
    before,
    between,
    char_in,
    char_not_in,
    char_range,
    create,
    exactly,
    group,
    non_capturing,
    not_after,
    not_before,
    one_or_more,
    optional,
    ref,
    scoped,
    times,
    unicode_property,
    zero_or_more,
)
from .pattern import Pattern

try:
    __version__ = metadata.version("remagic")
except metadata.PackageNotFoundError:  # pragma: no cover
    __version__ = "0+unknown"

__all__ = [
    "CARRIAGE_RETURN",
    "CHAR",
    "DIGIT",
    "END",
    "END_OF_STRING",
    "LETTER",
    "NEWLINE",
    "NOT_DIGIT",
    "NOT_LETTER",
    "NOT_N",
    "NOT_NEWLINE",
    "NOT_WHITESPACE",
    "NOT_WORD",
    "NOT_WORD_BOUNDARY",
    "NOT_WS",
    "START",
    "START_OF_STRING",
    "TAB",
    "WHITESPACE",
    "WORD",
    "WORD_BOUNDARY",
    "WS",
    "N",
    "Pattern",
    "R",
    "RemagicException",
    "__version__",
    "after",
    "any_of",
    "at_least",
    "atomic",
    "before",
    "between",
    "char_in",
    "char_not_in",
    "char_range",
    "create",
    "exactly",
    "group",
    "non_capturing",
    "not_after",
    "not_before",
    "one_or_more",
    "optional",
    "ref",
    "scoped",
    "times",
    "unicode_property",
    "zero_or_more",
]
